### ISSUE TITLE
Imprecise Ray Cast

### ISSUE THREAD

**Issue by Ludwig-Graef** [sampotter/python-embree#20]
Hi, 
I struggle a bit with the API of this library. 
I managed to cast a ray and return the first intersection point. Unfortunately, the result is a bit imprecise (~1.01-05). 
Is there a way of forcing `embree` to produce **more precise results**? 

Here is my code: 

```
def cast_rays(mesh: trimesh.Trimesh, ray_origins: np.ndarray, ray_directions: np.ndarray) -> np.ndarray:
        verts = np.array(mesh.vertices, dtype=np.float32)
        faces = mesh.faces.astype(np.uint32)

        device = embree.Device()
        scene = device.make_scene()
        geometry = device.make_geometry(embree.GeometryType.Triangle)

        vertex_buffer = geometry.set_new_buffer(embree.BufferType.Vertex, 0, embree.Format.Float3,
                                                3 * np.dtype('float32').itemsize, verts.shape[0])
        vertex_buffer[:] = verts[:]

        index_buffer = geometry.set_new_buffer(embree.BufferType.Index, 0, embree.Format.Uint3,
                                               3 * np.dtype('uint32').itemsize, faces.shape[0])
        index_buffer[:] = faces[:]

        geometry.commit()
        scene.attach_geometry(geometry)
        geometry.release()
        scene.commit()

        rayhit = embree.RayHit1M(len(ray_origins))
        rayhit.org[:] = ray_origins
        rayhit.dir[:] = ray_directions
        rayhit.tnear[:] = 0
        rayhit.tfar[:] = np.inf
        rayhit.flags[:] = 0
        rayhit.geom_id[:] = embree.INVALID_GEOMETRY_ID

        context = embree.IntersectContext()
        scene.intersect1M(context, rayhit)

        ray_inter = rayhit.geom_id != embree.INVALID_GEOMETRY_ID
        prim_id = rayhit.prim_id[ray_inter]
        u = rayhit.uv[:, 0][ray_inter]
        v = rayhit.uv[:, 1][ray_inter]
        w = 1 - u - v
        pts_xyz = np.vstack(w) * mesh.triangles[prim_id][:, 0, :] + np.vstack(
            u) * mesh.triangles[prim_id][:, 1, :] + np.vstack(v) * mesh.triangles[prim_id][:, 2, :]
        return pts_xyz
```

Versions: 
- embree 0.0.4
- Python 3.8.13
- Ubuntu 22.04

**Comment by sampotter** [comment]
Unfortunately, this is a limitation of Embree itself, not the python-embree wrapper library.

Embree is single precision. In general, one can expect relative error on the order of single-precision machine epsilon, which is about 1.2e-7.

I don't know whether the 1e-5 error you quote is absolute error or relative error, since you didn't specify. If this is absolute error, this very well could be the best possible error you can achieve with Embree. If it is relative error, then the magnitude is a bit large. 

If the error is indeed too large, there are ways you can "polish" the result. For your triangle mesh, you can first use Embree to determine a hit triangle for a given ray, and then simply intersect the ray and triangle in double precision to obtain a double-precision accurate result. It is unlikely this will cause any problems with the accuracy of visibility queries.

Another approach would be to use a library like CGAL, but it tends to run significantly slower than Embree.

Please let me know if you need any more help.
