### ISSUE TITLE
Citation (bibtex)?

### ISSUE THREAD

**Issue by aluo-x** [sampotter/python-embree#9]
A recent project of mine has used this library pretty extensively, I would like to cite this tool.

Is there a citation and/or a paper where you use this tool?

For example: Trimesh has this citation in their [github](https://github.com/mikedh/trimesh) (see bottom of page)

```
@software{trimesh,
	author = {{Dawson-Haggerty et al.}},
	title = {trimesh},
	url = {https://trimsh.org/},
	version = {3.2.0},
	date = {2019-12-8},
}
```

**Comment by sampotter** [comment]
I would be very happy if you did that, of course. ;-)

Do you need me to figure this out for you quickly? I think there are quick and easy ways to turn this around, just let me know when you'd like something you can cite.

**Comment by aluo-x** [comment]
Thanks for the reponse! Ideally before next wednesday, but I can also add the citation to the open access version (once the review period is over in a couple of months).

**Comment by sampotter** [comment]
I went ahead and followed [these instructions](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/referencing-and-citing-content) to make a DOI for this repository using Zenodo. I think this is probably a fine way to do it. I looked into e.g. The Journal of Open Source software and they explicitly say that they won't publish libraries that are just thin wrapper libraries, which makes sense to me. I think other "quick to publish software journals" are the same. 

I guess I feel a little weird about this non-research software that I wrote being cited (when I write actual research software...), but if it gets a few more eyeballs on this repository so that Embree can have a nice and properly developed Python wrapper, I'm all for it.

The DOI isn't active at the moment, but it should soon... Before you cite it, please let me know how the citation looks so I can make sure everything seems OK.

**Comment by aluo-x** [comment]
Much appreciated! 

The project is a computer vision/deep learning project, and your code is a key part of the project. 

I don't really consider this wrapper to be a trivial project, since I wouldn't even know where to start writing something like this. You only have to look at the (long) bug thread in Trimesh complaining about embree (v2)'s lack of accuracy completely breaking a ton of stuff. 

[trimesh#242](https://github.com/mikedh/trimesh/issues/242)
[trimesh#1180](https://github.com/mikedh/trimesh/issues/1180)
[trimesh#545](https://github.com/mikedh/trimesh/issues/545)

and the ongoing effort to migrate to your project:
[trimesh#1108](https://github.com/mikedh/trimesh/pull/1108)

Your embree3 wrapper completely mitigates the issues I had with embree2.

Will add the citation once the paper is closer to completion, and check in with you.

**Comment by sampotter** [comment]
Glad to hear it's been useful. :-)

I invited myself into your conversation over on the trimesh repo to see if there's any way I can help. I also use trimesh from time to time. Seems like it would be a good idea to get python-embree integrated into a project with a bit more traction.

**Comment by aluo-x** [comment]
Sorry, past few days have been a blur. 

Here is the citation: https://imgur.com/a/axRUdhb

**Comment by sampotter** [comment]
No problem! I did put together a DOI, see above. Not sure if your citation included that or not, but there you are. Hope your submission went off without a hitch!

**Comment by aluo-x** [comment]
I think the default citation style is just like that w/o the DOI, not super sure why a URL was not included. But I can likely still revise this down the line (for the open access version on arxiv). I can close the issue for now.

**Comment by sampotter** [comment]
Hi @aluo-x, I was curious whether you ever got this sorted out?

**Comment by aluo-x** [comment]
I did add the citation in the paper posted on arxiv:
https://arxiv.org/pdf/2201.00112.pdf

See citation 42 ([42] Samuel F. Potter. sampotter/python-embree:, Mar. 2021. 6). Ultimately I did not have time to port the Trimesh intersection tester to your embree implementation due to time constraints.
